### ISSUE TITLE
Project Proposal

### ISSUE THREAD

**Issue by mayankkuthar** [mayankkuthar/Project-Enron#1]
## Task to be done:  :octocat: 

- [x] Create a Project Proposal In PDF format.
- [x] Added the Proposal file respect Docs folder.
- [x] Use the Format Attached.

### Attachment:
[1. Project Proposal_Format.docx](https://github.com/mayankkuthar/Project-Enron/files/10881855/1.Project.Proposal_Format.docx)

**Comment by mayankkuthar** [comment]
Done :octocat:
