### ISSUE TITLE
Project Synopsis

### ISSUE THREAD

**Issue by mayankkuthar** [mayankkuthar/Project-Enron#2]
## Task to be done:  :octocat: 

- [x] Create a Project Synopsis In PDF format.
- [x] Added the Synopsis file in the respect Docs folder.
- [x] Use the Format Attached.

### Attachment:
[Synopsis_Format.docx](https://github.com/mayankkuthar/Project-Enron/files/10881866/Synopsis_Format.docx)

**Comment by Yamini09-code** [comment]
[Synopsis_Enron (1).docx](https://github.com/mayankkuthar/Project-Enron/files/10892205/Synopsis_Enron.1.docx)

Added Synopsis with required format

**Comment by mayankkuthar** [comment]
Done :octocat:
