### ISSUE TITLE
Research Article | Introduction

### ISSUE THREAD

**Issue by mayankkuthar** [mayankkuthar/Project-Enron#3]
## Task to be done:  :octocat: 

- [x] Create a Research Article ```Introduction``` section In PDF format.
- [x] Added the Article ```Introduction``` section file in the respective Docs folder.
- [x] Use the Format Attached.

### Attachment:
[ Research Article_Format.docx :octocat:  ](https://github.com/mayankkuthar/Project-Enron/files/10881899/4.Research.Article_Format.docx)

**Comment by mayankkuthar** [comment]
Done :octocat:
